# -*- coding: utf-8 -*-
"""英文队名 → 中文显示名"""

TEAM_NAME_CN = {
    # 英超
    "Arsenal FC": "阿森纳", "Manchester City FC": "曼城", "Liverpool FC": "利物浦",
    "Manchester United FC": "曼联", "Chelsea FC": "切尔西", "Tottenham Hotspur FC": "热刺",
    "Newcastle United FC": "纽卡斯尔", "Brighton & Hove Albion FC": "布莱顿",
    "Aston Villa FC": "阿斯顿维拉", "West Ham United FC": "西汉姆",
    "Brentford FC": "布伦特福德", "Fulham FC": "富勒姆",
    "Crystal Palace FC": "水晶宫", "Wolverhampton Wanderers FC": "狼队",
    "Everton FC": "埃弗顿", "Nottingham Forest FC": "诺丁汉森林",
    "Luton Town FC": "卢顿", "Burnley FC": "伯恩利", "Sheffield United FC": "谢菲尔德联",
    "AFC Bournemouth": "伯恩茅斯", "Leicester City FC": "莱斯特城",
    "Ipswich Town FC": "伊普斯维奇", "Southampton FC": "南安普顿",
    "Sunderland AFC": "桑德兰", "Leeds United FC": "利兹联",
    # 西甲
    "Real Madrid CF": "皇家马德里", "FC Barcelona": "巴塞罗那",
    "Atlético de Madrid": "马德里竞技", "Sevilla FC": "塞维利亚",
    "Valencia CF": "瓦伦西亚", "Real Betis Balompié": "贝蒂斯",
    "Real Sociedad de Fútbol": "皇家社会", "Athletic Club": "毕尔巴鄂竞技",
    "Villarreal CF": "比利亚雷亚尔", "Celta de Vigo": "塞尔塔",
    "Getafe CF": "赫塔费", "CA Osasuna": "奥萨苏纳",
    "Rayo Vallecano de Madrid": "拉约巴列卡诺", "UD Almería": "阿尔梅里亚",
    "Cadiz CF": "加的斯", "RCD Mallorca": "马略卡", "Girona FC": "赫罗纳",
    "UD Las Palmas": "拉斯帕尔马斯", "Deportivo Alavés": "阿拉维斯",
    "Real Valladolid CF": "巴利亚多利德", "Real Oviedo": "奥维耶多",
    "RCD Espanyol de Barcelona": "西班牙人",
    # 意甲
    "FC Internazionale Milano": "国际米兰", "AC Milan": "AC米兰",
    "Juventus FC": "尤文图斯", "SSC Napoli": "那不勒斯",
    "AS Roma": "罗马", "SS Lazio": "拉齐奥", "Atalanta BC": "亚特兰大",
    "ACF Fiorentina": "佛罗伦萨", "Bologna FC 1909": "博洛尼亚",
    "Torino FC": "都灵", "Udinese Calcio": "乌迪内斯",
    "Genoa CFC": "热那亚", "Cagliari Calcio": "卡利亚里",
    "Hellas Verona FC": "维罗纳", "Frosinone Calcio": "弗罗西诺内",
    "US Lecce": "莱切", "Empoli FC": "恩波利", "US Sassuolo Calcio": "萨索洛",
    "Monza": "蒙扎", "Venezia FC": "威尼斯", "Parma Calcio 1913": "帕尔马",
    "Como 1907": "科莫", "AC Monza": "蒙扎",
    # 德甲
    "FC Bayern München": "拜仁慕尼黑", "Borussia Dortmund": "多特蒙德",
    "RB Leipzig": "莱比锡", "Bayer 04 Leverkusen": "勒沃库森",
    "VfB Stuttgart": "斯图加特", "Eintracht Frankfurt": "法兰克福",
    "VfL Wolfsburg": "沃尔夫斯堡", "SC Freiburg": "弗莱堡",
    "Borussia Mönchengladbach": "门兴格拉德巴赫", "SV Werder Bremen": "不莱梅",
    "Union Berlin": "柏林联合", "VfL Bochum 1848": "波鸿",
    "Augsburg FC": "奥格斯堡", "1. FC Köln": "科隆",
    "SV Darmstadt 98": "达姆施塔特", "1. FC Heidenheim 1846": "海登海姆",
    "FC St. Pauli 1910": "圣保利", "Holstein Kiel": "基尔",
    "1. FC Union Berlin": "柏林联合",
    # 法甲
    "Paris Saint-Germain FC": "巴黎圣日耳曼", "Olympique de Marseille": "马赛",
    "AS Monaco FC": "摩纳哥", "Olympique Lyonnais": "里昂",
    "OGC Nice": "尼斯", "Stade Rennais FC": "雷恩",
    "RC Lens": "朗斯", "LOSC Lille": "里尔",
    "Toulouse FC": "图卢兹", "RC Strasbourg Alsace": "斯特拉斯堡",
    "Stade de Reims": "兰斯", "Montpellier HSC": "蒙彼利埃",
    "FC Nantes": "南特", "Clermont Foot 63": "克莱蒙",
    "FC Lorient": "洛里昂", "Le Havre AC": "勒阿弗尔",
    "Stade Brestois 29": "布雷斯特", "FC Metz": "梅斯",
    "Angers SCO": "昂热",
    # 欧冠额外球队
    "Club Brugge KV": "布鲁日", "SL Benfica": "本菲卡", "FC Porto": "波尔图",
    "Sporting CP": "体育CP", "Borussia Dortmund": "多特蒙德",
    "Real Madrid CF": "皇家马德里", "FC Barcelona": "巴塞罗那",
    "FC Bayern München": "拜仁慕尼黑", "Paris Saint-Germain FC": "巴黎圣日耳曼",
    "Inter Milan": "国际米兰", "AC Milan": "AC米兰",
    # 巴甲
    "CR Flamengo": "弗拉门戈", "SE Palmeiras": "帕尔梅拉斯",
    "SC Corinthians Paulista": "科林蒂安", "Fluminense FC": "弗鲁米嫩塞",
    "SC Internacional": "国际体育", "Grêmio FBPA": "格雷米奥",
    "CR Vasco da Gama": "瓦斯科达伽马", "Botafogo FR": "博塔福戈",
    "CA Mineiro": "米内罗竞技", "Cruzeiro EC": "克鲁塞罗",
    "CA Paranaense": "巴拉纳竞技", "Santos FC": "桑托斯",
    "São Paulo FC": "圣保罗", "EC Bahia": "巴伊亚",
    "Mirassol FC": "米拉索尔", "RB Bragantino": "布拉干蒂诺",
    "Coritiba FBC": "科里蒂巴", "EC Vitória": "维多利亚",
    "Chapecoense AF": "沙佩科恩塞", "Clube do Remo": "雷莫",
    # 解放者杯
    "CA Boca Juniors": "博卡青年", "CA River Plate": "河床",
    "CA Peñarol": "佩尼亚罗尔", "Club Nacional de Football": "国民队",
    "Estudiantes de La Plata": "拉普拉塔学生", "CA Rosario Central": "罗萨里奥中央",
    "CA Lanús": "拉努斯", "CA Platense": "普拉滕塞",
    "Club Bolívar": "玻利瓦尔", "Club Always Ready": "永远准备",
    "Club Cerro Porteño": "塞罗港", "Club Libertad Asuncion": "自由队",
    "CAR Independiente del Valle": "独立山谷", "LDU de Quito": "独立基多",
    "Barcelona SC": "厄瓜多尔巴塞罗那", "CD Universidad Católica": "天主教大学",
    "CS Cristal": "水晶体育", "Club Universitario de Deportes": "利马大学",
    "Cusco FC": "库斯科", "CDP Junior FC": "后卫竞技",
    "CD Independiente Medellín": "麦德林独立", "Independiente Santa Fe": "圣菲独立",
    "CD Tolima": "托利马", "Deportivo La Guaira FC": "拉瓜伊拉",
    "CD Coquimbo Unido": "科金博联合", "CS Independiente Rivadavia": "独立里瓦达维亚",
    "Universidad Central de Venezuela FC": "委内瑞拉中央大学",
}
